config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "about", to: "static_pages#about"
  get "contact_us", to: "static_pages#contact_us"
  get "help", to: "static_pages#help"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :military_times
  resources :craps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/craps.rb
class Craps < ApplicationRecord
end

app/models/funds.rb
class Funds < ApplicationRecord
  def amount_in_dollars
    amount / 100
  end
end

app/models/military_time.rb
class MilitaryTime < ApplicationRecord
  validates :military_time, presence: true, uniqueness: true,
    numericality: { only_integer: true, less_than: 2400, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/craps_controller.rb
class CrapsController < ApplicationController
  def show
    @craps = Craps.find(params[:id])
  end

  def index
    @craps = Craps.all
  end

  def destroy
  end

  def new
  end

  def create
  end
end

app/controllers/military_times_controller.rb
class MilitaryTimesController < ApplicationController
  def show
    @military_time = MilitaryTime.find(params[:id])
  end

  def index
    @military_times = MilitaryTime.all
  end

  def destroy
    @military_time = MilitaryTime.find(params[:id])
    @military_time.destroy
    redirect_to military_times_path
  end

  def new
    @military_time = MilitaryTime.new
  end

  def create
    military_time = military_time_params[:military_time]
    @military_time = MilitaryTime.new(military_time: military_time)
    begin
      @military_time.standard_time = MilitaryTimeConversion.new(military_time).standard_time
    rescue ConversionError => e
      @military_time.errors.add(:military_time, e.message)
    end
    if @military_time.errors.blank? && @military_time.save
      flash[:success] = "Military time conversion successfully created"
      redirect_to @military_time
    else
      flash.now[:danger] = "An error occured while converting the military time. Please try again"
      render :new
    end
  end

  private

  def military_time_params
    params.require(:military_time).permit(:military_time)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact_us
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_flash_messages(flash)
    content = ""
    flash.each do |message_type, message|
      content += tag.div(class: "alert alert-#{message_type}") do
        tag.p(message)
      end
    end
    content.html_safe
  end
end

app/helpers/craps_helper.rb
module CrapsHelper
end

app/helpers/military_times_helper.rb
module MilitaryTimesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/craps/_craps.html.erb
<p>Rolls: <%= craps.rolls %></p>
<% if craps.win %>
  <p>You won!</p>
<% else %>
  <p>You lost.</p>
<% end %>
<%= link_to("More information", craps )%>

app/views/craps/create.html.erb
<h1>Craps#create</h1>
<p>Find me in app/views/craps/create.html.erb</p>

app/views/craps/destroy.html.erb
<h1>Craps#destroy</h1>
<p>Find me in app/views/craps/destroy.html.erb</p>

app/views/craps/index.html.erb
<h1>All craps games</h1>
<%= render @craps %>
<br>
<%= link_to "Homepage", root_path %>

app/views/craps/new.html.erb
<h1>Craps#new</h1>
<p>Find me in app/views/craps/new.html.erb</p>

app/views/craps/show.html.erb
<h1>More information</h1>
<p><strong>Rolls</strong> <%= @craps.rolls %></p>
<% if @craps.win %>
  <p>Won</p>
<% else %>
  <p>Lost</p>
<% end %>
<p><strong>Created at:</strong> <%= @craps.created_at %></p>
<p><strong>Updated at:</strong> <%= @craps.updated_at %></p>
<%= link_to "Craps", craps_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApps</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= display_flash_messages(flash) %>
    <%= yield %>
  </body>
</html>

app/views/military_times/_form.html.erb
<%= form_with(model: military_time, local: true) do |f| %>
  <%= f.label :military_time %>
  <%= f.number_field :military_time, placeholder: "1300", autofocus: true, min: 0, max: 2359 %>

  <%= f.submit "Convert Time", class: "btn btn-primary" %>
<% end %>

app/views/military_times/_military_time.html.erb
<p>Military time: <%= military_time.military_time %></p>
<p>Standard time: <%= military_time.standard_time %></p>
<li>
  <%= link_to("\u{1F5D1}", military_time, method: :delete,
    data:{confirm: "Are you sure you want to delete this conversion?"},
      class: "btn btn-danger") %>
  &nbsp;
  <%= link_to("More information", military_time )%>
</li>

app/views/military_times/index.html.erb
<h1>All military time conversions</h1>
<%= render @military_times %>
<br>
<%= link_to "Homepage", root_path %>
<%= link_to "Create new conversion", new_military_time_path  %>

app/views/military_times/new.html.erb
<%= render "shared/error_messages", model: @military_time%>
<%= render "form", military_time: @military_time %>

app/views/military_times/show.html.erb
<h1>More information</h1>
<p><strong>Military time:</strong> <%= @military_time.military_time %></p>
<p><strong>Standard time:</strong> <%= @military_time.standard_time %></p>
<p><strong>Created at:</strong> <%= @military_time.created_at %></p>
<p><strong>Updated at:</strong> <%= @military_time.updated_at %></p>
<%= link_to "Military times", military_times_path%>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li> 
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>Morbi et vestibulum neque. Nam nulla justo, suscipit quis convallis in, elementum nec felis. Ut rutrum vel turpis eget lobortis. Donec sed facilisis diam. Nunc vel tortor facilisis, ultricies nisi sit amet, placerat mauris. Donec id mauris a eros lobortis pulvinar. Duis sed enim eget massa dictum molestie. Duis finibus nibh ac metus facilisis, non lobortis mi ultrices. Nullam varius lacus felis, nec efficitur lacus gravida sed. Morbi laoreet mi eros, quis malesuada justo dapibus id.</P>
<%= link_to "Home", root_path %>
<%= link_to "Help", help_path %>
<%= link_to "Contact us", contact_us_path %>

app/views/static_pages/contact_us.html.erb
<h1>Contact us</h1>
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
<%= link_to "Home", root_path %>
<%= link_to "About", about_path %>
<%= link_to "Help", help_path %>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat</p>
<%= link_to "Home", root_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact us", contact_us_path %>

app/views/static_pages/home.html.erb
<h1>My apps</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</P>
<%= link_to "MilitaryTime", military_times_path%>
<%= link_to "Craps", craps_index_path %>
<%= link_to "About", about_path %>
<%= link_to "Help", help_path %>
<%= link_to "Contact us", contact_us_path %>